### ISSUE TITLE
Can't build .pdf

### ISSUE THREAD

**Issue by lnikon** [ept/dist-sys#1]
Here is of output of `make`:
`This is BibTeX, Version 0.99d (TeX Live 2020/Arch Linux)
The top-level auxiliary file: dist-sys-notes.aux
I couldn't open style file plainurl.bst
---line 25 of file dist-sys-notes.aux
 : \bibstyle{plainurl
 :                   }
I'm skipping whatever remains of this command
I found no style file---while reading file dist-sys-notes.aux
(There were 2 error messages)
make: *** [Makefile:10: dist-sys-notes.bbl] Error 2
rm dist-sys-notes.aux dist-sys-slides.aux dist-sys-handout.aux`

I'm using:
`pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.90.0`

**Comment by ept** [comment]
Hi! That's odd — the `plainurl` bibliography style should be [part of a standard latex/bibtex distribution](https://www.bibtex.com/s/bibliography-style-urlbst-plainurl/). How did you install latex on your machine?

You can try dropping [this file](http://tug.ctan.org/biblio/bibtex/contrib/urlbst/plainurl.bst) in the current directory and running `make` again.

I should point out that there is not yet much material in this repository, so it's not really worth looking at yet!
